#5 simulate wind and power generation
PandaFood/M7011E_EnergySystem pull request #8
Opened 2019-11-08 10:04 UTC by 97gushan

Adding issue #5, simulating wind and power generation

2019-11-08 12:39 UTC, 97gushan commented
New power calculation function is based on the power output profile graph in: [Wind Statistics](http://www.wind-power-program.com/wind_statistics.htm)

2019-11-12 13:36 UTC, PandaFood requested changes
Should testSigmoid.csv really be included?

2019-11-12 13:36 UTC, PandaFood commented on Simulator/routes/api.js
> +var Simulator = require("../simulation/simulator");
Avoid var in ES6

2019-11-12 13:36 UTC, PandaFood commented on Simulator/simulation/simulator.js
> +
Is this beautified?
Lots of unnecessary  empty space

2019-11-12 15:06 UTC, PandaFood approved these changes

2019-11-12 15:07 UTC, merged